
AWSTemplateFormatVersion: '2010-09-09'
Description: NextCloud ECS Infrastructure
Parameters:
  #------------------------
  # Deployment Information
  #------------------------
  environment:
    Type: String
    Description: Name of the environment to use in naming.
    Default: production
  release:
    Type: String
    Description: Name of the release name of the stack version to use.
    Default: production
    AllowedValues: ['develop', 'stage', 'production']
    ConstraintDescription: "Must be a possible release version."
  AsgDesiredCapacity:
    Type: Number
    Default: 1

  #------------
  # Networking
  #------------
  VpcId:
    Description: ID of the VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Description: The public subnets for the ALB to run in. (Space seperated)
    Type: String
  AcmCertificate:
    Description: HTTPS Cert from Amazon Certificate Manager
    Type: String

  #------------
  # CloudWatch
  #------------
  LogGroup:
    Type: String
    Description: The AWS CloudWatch log group to output logs to.
    Default: "/ecs/nextcloud"

Resources:

  LoadBalancing:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.us-east-1.amazonaws.com/sumu-stacks/nextcloud/${release}/cloudformation/nextcloud/load_balancing.yaml'
      Parameters:
        environment: !Ref environment
        VpcId: !Ref VpcId
        PublicSubnets: !Join [",", !Split [" ", !Ref PublicSubnets]]
        AcmCertificate: !Ref AcmCertificate

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.us-east-1.amazonaws.com/sumu-stacks/nextcloud/${release}/cloudformation/nextcloud/iam.yaml'
      Parameters:
        environment: !Ref environment

  EcsCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.us-east-1.amazonaws.com/sumu-stacks/nextcloud/${release}/cloudformation/cluster/top.yaml'
      Parameters:
        Environment: !Ref environment
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Split [" ", !Ref PublicSubnets]]
        Project: "NextCloud"
        AsgDesiredCapacity: !Ref AsgDesiredCapacity
        InstanceType: t3a.micro

  TaskDefinition:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.us-east-1.amazonaws.com/sumu-stacks/nextcloud/${release}/cloudformation/nextcloud/task.yaml'
      Parameters:
        environment: !Ref environment
        LogGroupName: !Ref LogGroup
        DockerTag: "latest"
        TaskExecutionRole: !GetAtt IAM.Outputs.EcsExecutioner

  EcsService:
    DependsOn: LoadBalancing
    Type: AWS::ECS::Service
    Properties:
      Cluster: !GetAtt EcsCluster.Outputs.Cluster
      DesiredCount: 1
      TaskDefinition: !GetAtt TaskDefinition.Outputs.TaskArn
      LoadBalancers:  
        - ContainerName: "nextcloud"
          ContainerPort: 80
          TargetGroupArn: !GetAtt LoadBalancing.Outputs.AlbTargetGroup