name: Build Stage

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  cloudformation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.1.0
    - name: Ship to CloudFormation S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        SOURCE_DIR: cloudformation
        AWS_REGION: "us-east-2"
        DEST_DIR: nextcloud/production/cloudformation
        AWS_S3_BUCKET: sumu-stacks
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}